### ISSUE TITLE
Broken UI at Sponsors block on Windows Phone

### ISSUE THREAD

**Issue by Mevrael** [psihius/webconf#3]
Screenshot - https://drive.google.com/file/d/0B87u03g8AvAOYWJHZlVCdVpxOTQ/view?usp=sharing

**Device:**
Microsoft Lumia 640
Windows Phone 8.1 Update 2
Default browser

**Comment by seleckis** [comment]
Please check again. Must be fixed.

**Comment by seleckis** [comment]
It seems it is fixed 281727995639a6866e7c650e151fb4acff5b0975
